site_name: melody.web
site_author: MelodyKit
site_description: All your music, in one place.

repo_name: MelodyKit/melody.web
repo_url: https://github.com/MelodyKit/melody.web

remote_branch: github-pages

nav:
  - Index: "index.md"
  - Reference:
    - Melody:
      - Kit:
        - Core: "reference/melody/kit/core.md"
  - Changelog: "changelog.md"
  - Security: "security.md"
  - Code of Conduct: "code_of_conduct.md"
  - Contributing: "contributing.md"

watch:
  - docs
  - melody

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate

      primary: deep purple
      accent: light blue

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default

      primary: light blue
      accent: deep purple

      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

plugins:
  - search

  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

          paths: [melody]

          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
