[tool.poetry]
name = "melody.web"
version = "0.1.1"
description = "All your music, in one place."
authors = ["MelodyKit"]
license = "MIT"

readme = "README.md"

homepage = "https://melodykit.app/"
repository = "https://github.com/MelodyKit/melody.web"

keywords = ["python", "api", "kit", "web"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.urls]
Discord = "https://melodykit.app/discord"
Issues = "https://github.com/MelodyKit/melody.web/issues"

[[tool.poetry.packages]]
include = "melody"

[tool.poetry.scripts]
"melody.kit" = "melody.kit.main:run"
"melody.web" = "melody.web.main:web"

[tool.poetry.dependencies]
python = ">= 3.7"
httpx = ">= 0.23.3"
fastapi = ">= 0.89.1"
jinja2 = ">= 3.1.2"
python-multipart = ">= 0.0.5"
toml = ">= 0.10.2"
pendulum = ">= 2.1.2"
edgedb = ">= 1.2.0"
iters = ">= 0.10.0"
wraps = ">= 0.2.0"
pyjwt = ">= 2.6.0"
argon2-cffi = ">= 21.3.0"
click = ">= 8.1.3"
entrypoint = ">= 1.3.0"
email-validator = ">= 1.3.1"
async-extensions = ">= 1.2.0"

[tool.poetry.dependencies.aiosmtplib]
version = ">= 2.0.1"
python = "^3.7"

[tool.poetry.dependencies.qrcode]
version = ">= 7.3.1"
extras = ["pil"]

[tool.poetry.dependencies.uvicorn]
version = ">= 0.20.0"
extras = ["standard"]

[tool.poetry.group.format]
optional = true

[tool.poetry.group.format.dependencies]
black = "22.12.0"

[tool.poetry.group.format.dependencies.isort]
version = "5.11.4"

[tool.poetry.group.check]
optional = true

[tool.poetry.group.check.dependencies]
mypy = "0.991"

[tool.black]
line_length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
show_column_numbers = true

disallow_any_decorated = true
disallow_any_generics = true
warn_return_any = true

no_implicit_optional = true
strict_optional = true

strict_equality = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
disallow_untyped_globals = true

disallow_incomplete_defs = true

warn_no_return = true
warn_unreachable = true

warn_redundant_casts = true
warn_unused_ignores = false  # compatibility

[tool.changelogging]
name = "melody.web"
version = "0.1.1"
url = "https://github.com/MelodyKit/melody.web"
directory = "changes"
output = "CHANGELOG.md"

start_string = "<!-- changelogging: start -->"

title_format = "{version} ({date})"
issue_format = "[#{issue}]({url}/pull/{issue})"

bullet = "-"
wrap = true
wrap_size = 100

display = ["feature", "change", "fix", "security", "deprecation", "removal", "internal"]

[build-system]
requires = ["poetry-core >= 1.4.0"]
build-backend = "poetry.core.masonry.api"
