[tool.poetry]
name = "melody.web"
version = "0.1.1"
description = "All your music, in one place."
authors = ["MelodyKit"]
license = "MIT"

readme = "README.md"

homepage = "https://melodykit.app/"
repository = "https://github.com/MelodyKit/melody.web"

keywords = ["python", "api", "kit", "web"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.urls]
Discord = "https://melodykit.app/discord"
Issues = "https://github.com/MelodyKit/melody.web/issues"

[[tool.poetry.packages]]
include = "melody"

[tool.poetry.scripts]
"melody.bot" = "melody.bot.main:bot"
"melody.kit" = "melody.kit.main:run"
"melody.web" = "melody.web.main:web"

[tool.poetry.dependencies]
# melody
python = ">= 3.7"
versions = ">= 1.4.0"
attrs = ">= 23.1.0"
# melody.kit
fastapi = ">= 0.95.1"
toml = ">= 0.10.2"
pendulum = ">= 2.1.2"
edgedb = ">= 1.3.0"
iters = ">= 0.12.0"
redis = ">= 4.5.4"
argon2-cffi = ">= 21.3.0"
click = ">= 8.1.3"
entrypoint = ">= 1.4.0"
email-validator = ">= 2.0.0"
async-extensions = ">= 1.2.2"
colors-core = ">= 1.0.0"
typing-extensions = ">= 4.5.0"
# melody.web
jinja2 = ">= 3.1.2"
python-multipart = ">= 0.0.6"
# melody.shared
cattrs = "22.2.0"  # ">= 23.2.0"
httpx = ">= 0.24.0"
typing-aliases = ">= 1.1.3"

[tool.poetry.dependencies.aiosmtplib]  # melody.kit
version = ">= 2.0.1"
python = "^3.7"

[tool.poetry.dependencies.qrcode]  # melody.link
version = ">= 7.4.2"
extras = ["pil"]

[tool.poetry.dependencies.uvicorn]  # melody.kit
version = ">= 0.21.1"
extras = ["standard"]

[tool.poetry.dependencies."discord.py"]  # melody.bot
version = ">= 2.2.2"
python = ">= 3.8"

[tool.poetry.group.format]
optional = true

[tool.poetry.group.format.dependencies]
black = "23.3.0"
flake8-pyproject = "1.2.3"

[tool.poetry.group.format.dependencies.flake8]
version = "6.0.0"
python = ">= 3.8.1"

[tool.poetry.group.format.dependencies.isort]
version = "5.12.0"
python = ">= 3.8"

[tool.poetry.group.check]
optional = true

[tool.poetry.group.check.dependencies]
mypy = "1.4.1"
types-toml = "0.10.8.6"
types-redis = "4.6.0.1"

[tool.black]
line_length = 100

[tool.flake8]
max_line_length = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
show_column_numbers = true

disallow_any_decorated = true
disallow_any_generics = true
warn_return_any = true

no_implicit_optional = true
strict_optional = true

strict_equality = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
disallow_untyped_globals = true

disallow_incomplete_defs = true

warn_no_return = true
warn_unreachable = true

warn_redundant_casts = true
warn_unused_ignores = false  # compatibility

[tool.changelogging]
name = "melody.web"
version = "0.1.1"
url = "https://github.com/MelodyKit/melody.web"
directory = "changes"
output = "CHANGELOG.md"

start_string = "<!-- changelogging: start -->"

title_format = "{version} ({date})"
issue_format = "[#{issue}]({url}/pull/{issue})"

bullet = "-"
wrap = true
wrap_size = 100

display = ["feature", "change", "fix", "security", "deprecation", "removal", "internal"]

[build-system]
requires = ["poetry-core >= 1.5.2"]
build-backend = "poetry.core.masonry.api"
