[melody]
name = "MelodyKit"
domain = "melodykit.app"

[melody.email]
host = "smtp.gmail.com"
port = 587
support = "support@melodykit.app"

[melody.hash]
time_cost = 4
memory_cost = 65536
parallelism = 4

[melody.kit]
host = "127.0.0.1"
port = 1342
