# This is the default configuration file for MelodyKit.
# Configuration file is located at `~/.config/melody/kit.toml`.
# There are some sensitive fields that need to be manually defined:
# - `melody.email.name`
# - `melody.email.password`
# - `melody.bot.token`

[melody]
name = "MelodyKit"
domain = "melodykit.app"
open = "open"

images = "~/.melody/kit/images"

[melody.email]
host = "smtp.gmail.com"
port = 587
support = "support@melodykit.app"

[melody.hash]
time_cost = 4
memory_cost = 65536
parallelism = 4

[melody.kit]
host = "127.0.0.1"
port = 1342

[melody.link]
cache = "~/.cache/melody/link"
error_correction = "high"
box_size = 10
border = 4

[melody.log]
level = "info"

[melody.redis]
host = "127.0.0.1"
port = 6379

[melody.token]
type = "Bearer"

[melody.token.access]
size = 32

[melody.token.access.expires]
years = 0
months = 0
weeks = 0
days = 0
hours = 1
minutes = 0
seconds = 0

[melody.token.refresh]
size = 32

[melody.token.refresh.expires]
years = 0
months = 1
weeks = 0
days = 0
hours = 0
minutes = 0
seconds = 0

[melody.token.verification]
size = 32

[melody.token.verification.expires]
years = 0
months = 0
weeks = 0
days = 1
hours = 0
minutes = 0
seconds = 0

[melody.web]
host = "127.0.0.1"
port = 4269

[melody.bot]
