# This is the default configuration file for MelodyKit.
# Configuration file is located at `~/.config/melody/kit.toml`.
# You can read more about it here: `https://docs.melodykit.app/config`.

[access.expires]
hours = 1

[refresh.expires]
months = 1

[authorization.expires]
hours = 1

[verification.expires]
hours = 1
