DEFAULT_PATH = "~/.config/melody/kit.toml"

DEFAULT_NAME = "MelodyKit"
DEFAULT_DOMAIN = "melodykit.app"
DEFAULT_OPEN = "open"

DEFAULT_KEYRING_NAME = "melody.kit"
DEFAULT_KEYRING_SESSION = "session"
DEFAULT_KEYRING_EMAIL = "email"
DEFAULT_KEYRING_BOT = "bot"
DEFAULT_KEYRING_DISCORD = "discord"
DEFAULT_KEYRING_SPOTIFY = "spotify"

DEFAULT_EMAIL_HOST = "smtp.gmail.com"
DEFAULT_EMAIL_PORT = 587
DEFAULT_EMAIL_SUPPORT = "support@melodykit.app"

DEFAULT_EMAIL_VERIFICATION_SUBJECT = "{name}"
DEFAULT_EMAIL_VERIFICATION_CONTENT = "{link}"

DEFAULT_EMAIL_TEMPORARY_SUBJECT = "{name}"
DEFAULT_EMAIL_TEMPORARY_CONTENT = "{link}"

DEFAULT_HASH_TIME_COST = 4
DEFAULT_HASH_MEMORY_COST = 65536
DEFAULT_HASH_PARALLELISM = 4

DEFAULT_KIT_HOST = "127.0.0.1"
DEFAULT_KIT_PORT = 1342

DEFAULT_CODE_CACHE = "~/.cache/melody/kit"
DEFAULT_CODE_BOX_SIZE = 10
DEFAULT_CODE_BORDER = 4

DEFAULT_IMAGE_DIRECTORY = "~/.melody/kit/images"
DEFAULT_IMAGE_SIZE_LIMIT = 4096
DEFAULT_IMAGE_DATA_LIMIT = 16777216

DEFAULT_REDIS_HOST = "127.0.0.1"
DEFAULT_REDIS_PORT = 6379

DEFAULT_SECRET_SIZE = 32

DEFAULT_TOTP_DIGITS = 6
DEFAULT_TOTP_INTERVAL = 30
DEFAULT_TOTP_VALID_WINDOW = 1

DEFAULT_TOKEN_TYPE = "Bearer"

DEFAULT_EXPIRES_YEARS = 0
DEFAULT_EXPIRES_MONTHS = 0
DEFAULT_EXPIRES_WEEKS = 0
DEFAULT_EXPIRES_DAYS = 0
DEFAULT_EXPIRES_HOURS = 0
DEFAULT_EXPIRES_MINUTES = 0
DEFAULT_EXPIRES_SECONDS = 0

DEFAULT_ACCESS_SIZE = 32

DEFAULT_REFRESH_SIZE = 32

DEFAULT_AUTHORIZATION_SIZE = 32

DEFAULT_VERIFICATION_SIZE = 32

DEFAULT_WEB_HOST = "127.0.0.1"
DEFAULT_WEB_PORT = 4269

DEFAULT_OFFSET_DEFAULT = 0
DEFAULT_OFFSET_MIN = 0

DEFAULT_LIMIT_DEFAULT = 100
DEFAULT_LIMIT_MIN = 0
DEFAULT_LIMIT_MAX = 100
