select Playlist {
    id,
    name,
    owner: {
        id,
        name,
        follower_count,
        stream_count,
        created_at,
        spotify_id,
        apple_music_id,
        yandex_music_id,
        discord_id,
    },
    follower_count,
    description,
    track_count,
    created_at,
    spotify_id,
    apple_music_id,
    yandex_music_id,
} filter .id = <uuid>$playlist_id;
