[package]
name = "melody-chrono"
version = "0.1.0"
description = "MelodyKit time utilities."
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
