name: docs

on:
  push:
    branches:
      - main

env:
  python-version: "3.12"

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Install Poetry
        run: pipx install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Specify the version
        run: poetry env use python

      - name: Install dependencies
        run: poetry install --with docs

      - name: Pull
        run: git pull

      - name: Deploy the documentation
        run: poetry run mkdocs gh-deploy
