from melody.kit.endpoints.v1.albums import get_album, get_album_link, get_album_tracks
from melody.kit.endpoints.v1.artists import (
    get_artist,
    get_artist_albums,
    get_artist_link,
    get_artist_tracks,
)
from melody.kit.endpoints.v1.auth import (
    authorize,
    forgot,
    login,
    register,
    reset,
    revoke,
    revoke_all,
    tokens,
    verify,
)
from melody.kit.endpoints.v1.clients import create_client, delete_client, get_client, update_client
from melody.kit.endpoints.v1.playlists import (
    change_playlist_image,
    create_playlist,
    delete_playlist,
    get_playlist,
    get_playlist_image,
    get_playlist_link,
    get_playlist_tracks,
    remove_playlist_image,
    update_playlist,
)
from melody.kit.endpoints.v1.search import search_entities
from melody.kit.endpoints.v1.self import (
    add_self_followed_playlists,
    add_self_following,
    change_self_image,
    get_self,
    get_self_albums,
    get_self_artists,
    get_self_followed_playlists,
    get_self_followers,
    get_self_following,
    get_self_friends,
    get_self_image,
    get_self_link,
    get_self_playlists,
    get_self_settings,
    get_self_streams,
    get_self_tracks,
    remove_self_albums,
    remove_self_artists,
    remove_self_followed_playlists,
    remove_self_following,
    remove_self_image,
    remove_self_tracks,
    save_self_albums,
    save_self_artists,
    save_self_tracks,
    update_self_settings,
)
from melody.kit.endpoints.v1.statistics import get_statistics
from melody.kit.endpoints.v1.totp import (
    generate_totp,
    link_totp,
    remove_totp,
    verify_totp,
)
from melody.kit.endpoints.v1.tracks import get_track, get_track_link
from melody.kit.endpoints.v1.users import (
    get_user,
    get_user_albums,
    get_user_artists,
    get_user_followers,
    get_user_following,
    get_user_friends,
    get_user_image,
    get_user_link,
    get_user_playlists,
    get_user_tracks,
)

__all__ = (
    # tracks
    "get_track",
    "get_track_link",
    # artists
    "get_artist",
    "get_artist_link",
    "get_artist_tracks",
    "get_artist_albums",
    # albums
    "get_album",
    "get_album_link",
    "get_album_tracks",
    # playlists
    "create_playlist",
    "get_playlist",
    "update_playlist",
    "delete_playlist",
    "get_playlist_link",
    "get_playlist_image",
    "change_playlist_image",
    "remove_playlist_image",
    "get_playlist_tracks",
    # users
    "get_user",
    "get_user_link",
    "get_user_image",
    "get_user_tracks",
    "get_user_artists",
    "get_user_albums",
    "get_user_playlists",
    "get_user_followers",
    "get_user_following",
    "get_user_friends",
    # self
    "get_self",
    "get_self_link",
    "get_self_image",
    "change_self_image",
    "remove_self_image",
    "get_self_tracks",
    "save_self_tracks",
    "remove_self_tracks",
    "get_self_artists",
    "save_self_artists",
    "remove_self_artists",
    "get_self_albums",
    "save_self_albums",
    "remove_self_albums",
    "get_self_playlists",
    "get_self_streams",
    "get_self_friends",
    "get_self_followers",
    "get_self_following",
    "add_self_following",
    "remove_self_following",
    "get_self_followed_playlists",
    "add_self_followed_playlists",
    "remove_self_followed_playlists",
    "get_self_settings",
    "update_self_settings",
    # statistics
    "get_statistics",
    # TOTP
    "generate_totp",
    "remove_totp",
    "link_totp",
    "verify_totp",
    # auth
    "login",
    "authorize",
    "tokens",
    "revoke",
    "revoke_all",
    "register",
    "verify",
    "reset",
    "forgot",
    # search
    "search_entities",
    # clients
    "create_client",
    "get_client",
    "delete_client",
    "update_client",
)
